FROM node:16-alpine

WORKDIR /code

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the tests will run on
EXPOSE 3000

# Run the tests
CMD ["npm", "run"]